version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Mantiene la contraseña del usuario root
      MYSQL_DATABASE: inmuebledb  # Crea la base de datos automáticamente
      MYSQL_USER: user  # Define un usuario regular en lugar de root
      MYSQL_PASSWORD: password  # Contraseña del usuario regular
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: django_backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_NAME: inmuebledb
      DB_USER: user  # Asegúrate de usar el usuario que creaste en MySQL
      DB_PASSWORD: password
      DB_HOST: mysql
      DB_PORT: 3306
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    command: python manage.py runserver 0.0.0.0:8000  # Habilita recarga automática

  frontend:
    build: ./frontend
    container_name: vue_frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=0.0.0.0
    networks:
      - app_network
    command: npm run dev  # Habilita Hot Reload

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
